server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_rental
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000
      expire: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.coder.entity
  global-config:
    db-config:
      logic-delete-field: deleted

#密码加密配置
encoder:
  ctype:
    strength: 6
    secret: ${random.uuid}

request:
  login-url: /rental/user/login

